# Generated by Django 3.2.4 on 2021-09-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdeepen',
            old_name='staus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='cfinish',
            old_name='staus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='edeepen',
            old_name='staus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='efinish',
            old_name='staus',
            new_name='status',
        ),
    ]
